name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v6

      - name: Lint check
        run: nix-shell --run 'sbt -Dsbt.supershell=false ;fixCheck;fmtCheck'

      - run: nix-shell --run 'sbt -Dsbt.supershell=false test && sbt -Dsbt.sueprshell=false docs/mdoc'

      - name: Build website
        run: nix-shell --run 'sbt docs/docusaurusCreateSite'
